import { NextRequest } from "next/server";
import { auth } from "@/lib/auth";
import { generateTemplate } from "@/lib/template-generator";
import { createGitHubRepo, uploadFilesToRepo, repoExists } from "@/lib/github-repo-service";

export async function POST(request: NextRequest) {
  try {
    const session = await auth();

    if (!session?.accessToken) {
      return Response.json(
        {
          success: false,
          error: "Not authenticated or missing GitHub access token",
        },
        { status: 401 }
      );
    }

    const username = session.user.githubUsername;
    if (!username) {
      return Response.json(
        {
          success: false,
          error: "GitHub username not found in session",
        },
        { status: 400 }
      );
    }

    // Get GitHub data from request body (passed from client)
    const body = await request.json();
    const { githubData } = body;

    if (!githubData) {
      return Response.json(
        {
          success: false,
          error: "GitHub data is required",
        },
        { status: 400 }
      );
    }

    // Validate the GitHub data structure
    if (!githubData.profile || !githubData.profile.username) {
      return Response.json(
        {
          success: false,
          error: "Invalid GitHub data structure. Profile information is required.",
        },
        { status: 400 }
      );
    }

    // Generate repository name
    const repoName = `CrYOPS-${username}`;

    // Check if repo already exists
    const exists = await repoExists(session.accessToken, username, repoName);
    if (exists) {
      console.error(`Repository ${repoName} already exists. Please delete it first or use a different name.`);
      return Response.json(
        {
          success: false,
          error: `Repository ${repoName} already exists. Please delete it first or use a different name.`,
        },
        { status: 409 }
      );
    }

    // Generate template files
    const templateFiles = generateTemplate(githubData, username);

    // Create repository
    const repo = await createGitHubRepo(session.accessToken, {
      name: repoName,
      description: `${githubData.profile.name}'s portfolio site generated by CrYOPS`,
      private: false,
    });

    // Wait for repo to be fully created
    await new Promise((resolve) => setTimeout(resolve, 1500));

    // Upload all files
    const files = templateFiles.map((file) => ({
      path: file.path,
      content: file.content,
    }));

    // Upload files with progress tracking
    let uploadedCount = 0;
    await uploadFilesToRepo(
      session.accessToken,
      username,
      repoName,
      files,
      (current, total) => {
        uploadedCount = current;
        console.log(`Uploaded ${current}/${total} files`);
      }
    );
    console.log(`Uploaded ${uploadedCount} files to repository ${repoName}`);

    return Response.json({
      success: true,
      data: {
        repo: {
          name: repo.name,
          full_name: repo.full_name,
          html_url: repo.html_url,
          clone_url: repo.clone_url,
        },
        filesUploaded: uploadedCount,
        totalFiles: files.length,
      },
    });
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : String(error);
    console.error("[Deploy API] Error deploying repository:", errorMessage);

    return Response.json(
      {
        success: false,
        error: "An error occurred while deploying the repository. Please try again.",
      },
      { status: 500 }
    );
  }
}