/**
 * Service for creating GitHub repositories and uploading files
 */

export interface CreateRepoOptions {
  name: string;
  description?: string;
  private?: boolean;
}

export interface CreateRepoResponse {
  id: number;
  name: string;
  full_name: string;
  html_url: string;
  clone_url: string;
  default_branch: string;
}

/**
 * Create a new GitHub repository
 */
export async function createGitHubRepo(
  accessToken: string,
  options: CreateRepoOptions
): Promise<CreateRepoResponse> {
  const response = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers: {
      Authorization: `token ${accessToken}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
      "User-Agent": "CrYOPS",
    },
    body: JSON.stringify({
      name: options.name,
      description: options.description || "Portfolio site generated by CrYOPS",
      private: options.private || false,
      auto_init: false, // We'll create files manually
    }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: response.statusText }));
    throw new Error(
      `Failed to create repository: ${error.message || response.statusText} (${response.status})`
    );
  }

  return response.json();
}

/**
 * Upload a file to a GitHub repository using the Contents API
 */
export async function uploadFileToRepo(
  accessToken: string,
  owner: string,
  repo: string,
  path: string,
  content: string,
  message: string = `Add ${path}`
): Promise<void> {
  // Encode content as base64
  // Buffer is available in Node.js runtime (Next.js API routes)
  const encodedContent = Buffer.from(content, "utf-8").toString("base64");

  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
    {
      method: "PUT",
      headers: {
        Authorization: `token ${accessToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
        "User-Agent": "CrYOPS",
      },
      body: JSON.stringify({
        message,
        content: encodedContent,
      }),
    }
  );

  if (!response.ok) {
    const error = await response.json().catch(() => ({ message: response.statusText }));
    throw new Error(
      `Failed to upload file ${path}: ${error.message || response.statusText} (${response.status})`
    );
  }
}

/**
 * Upload multiple files to a GitHub repository
 * Uses sequential uploads to avoid rate limiting issues
 */
export async function uploadFilesToRepo(
  accessToken: string,
  owner: string,
  repo: string,
  files: Array<{ path: string; content: string }>,
  onProgress?: (current: number, total: number) => void
): Promise<void> {
  const total = files.length;
  let current = 0;

  for (const file of files) {
    current++;
    await uploadFileToRepo(
      accessToken,
      owner,
      repo,
      file.path,
      file.content,
      `Add ${file.path}`
    );
    onProgress?.(current, total);
    
    // Small delay to avoid rate limiting
    if (current < total) {
      await new Promise((resolve) => setTimeout(resolve, 5000));
    }
  }
}

/**
 * Check if a repository exists
 */
export async function repoExists(
  accessToken: string,
  owner: string,
  repo: string
): Promise<boolean> {
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
    method: "GET",
    headers: {
      Authorization: `token ${accessToken}`,
      Accept: "application/vnd.github.v3+json",
      "User-Agent": "CrYOPS",
    },
  });

  return response.ok;
}
