import type { GithubPublishData } from "@/lib/validations/github";
import type { TemplateConfig } from "@/types/template-config";
import { DEFAULT_TEMPLATE_CONFIG } from "./generator/default-config";
import { generateIndexCSS } from "./generator/generate-css";
import { generateAboutComponent } from "./generator/generate-about";
import { generateGitHubStatsComponent } from "./generator/generate-github-stats";

export interface TemplateFile {
  path: string;
  content: string;
}

/**
 * Generate a complete Vite + React portfolio template from GitHub data.
 * All visual properties (colors, typography, spacing, layout) are driven
 * by the TemplateConfig — no hardcoded values.
 */
export function generateTemplate(
  githubData: GithubPublishData,
  username: string,
  config: TemplateConfig = DEFAULT_TEMPLATE_CONFIG
): TemplateFile[] {
  const files: TemplateFile[] = [];

  // ── Scaffold files (infrastructure, not style-dependent) ──

  files.push({
    path: "package.json",
    content: JSON.stringify(
      {
        name: `cryops-portfolio-${username}`,
        private: true,
        version: "0.1.0",
        type: "module",
        engines: { node: "20.x" },
        scripts: {
          dev: "vite",
          build: "tsc && vite build",
          preview: "vite preview",
        },
        dependencies: {
          clsx: "^2.1.1",
          "lucide-react": "^0.562.0",
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          "react-github-calendar": "^5.0.4",
          "tailwind-merge": "^3.4.0",
        },
        devDependencies: {
          "@tailwindcss/postcss": "^4.1.18",
          "@types/react": "^18.2.0",
          "@types/react-dom": "^18.2.0",
          "@vitejs/plugin-react": "^4.2.0",
          autoprefixer: "^10.4.0",
          postcss: "^8.4.0",
          tailwindcss: "^4.0.0",
          typescript: "^5.0.0",
          vite: "^5.0.0",
        },
      },
      null,
      2
    ),
  });

  files.push({
    path: "vite.config.ts",
    content: `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`,
  });

  files.push({
    path: "tsconfig.json",
    content: JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
        },
        include: ["src"],
        references: [{ path: "./tsconfig.node.json" }],
      },
      null,
      2
    ),
  });

  files.push({
    path: "tsconfig.node.json",
    content: JSON.stringify(
      {
        compilerOptions: {
          composite: true,
          skipLibCheck: true,
          module: "ESNext",
          moduleResolution: "bundler",
          allowSyntheticDefaultImports: true,
        },
        include: ["vite.config.ts"],
      },
      null,
      2
    ),
  });

  files.push({
    path: "index.html",
    content: `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${githubData.profile.name} - Portfolio</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
  });

  files.push({
    path: ".gitignore",
    content: `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`,
  });

  files.push({
    path: "README.md",
    content: `# ${githubData.profile.name}'s Portfolio

Portfolio site generated by CrYOPS.

## Getting Started

\`\`\`bash
pnpm install
pnpm run dev
\`\`\`

## Build

\`\`\`bash
pnpm run build
\`\`\`

## Deploy

This site can be deployed to Vercel, Netlify, or any static hosting service.
`,
  });

  files.push({
    path: "tailwind.config.js",
    content: `/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`,
  });

  files.push({
    path: "postcss.config.js",
    content: `export default {
  plugins: {
    '@tailwindcss/postcss': {},
    autoprefixer: {},
  },
}

`,
  });

  files.push({
    path: "src/main.tsx",
    content: `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`,
  });

  files.push({
    path: "public/vite.svg",
    content: `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="31.88" height="32" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 257"><defs><linearGradient id="grad1" x1="-.828%" x2="57.636%" y1="7.652%" y2="78.411%"><stop offset="0%" stop-color="#41D1FF"></stop><stop offset="100%" stop-color="#BD34FE"></stop></linearGradient><linearGradient id="grad2" x1="43.376%" x2="50.316%" y1="2.242%" y2="89.03%"><stop offset="0%" stop-color="#FFEA83"></stop><stop offset="8.333%" stop-color="#FFDD35"></stop><stop offset="100%" stop-color="#FFA800"></stop></linearGradient></defs><path fill="url(#grad1)" d="M255.153 37.938L134.897 252.976c-2.483 4.44-8.862 4.466-11.382.048L.875 37.958c-2.746-4.814 1.371-10.646 6.827-9.67l120.385 21.517a6.537 6.537 0 0 0 2.322-.004l117.867-21.483c5.438-.991 9.666 4.796 6.877 9.62Z"></path><path fill="url(#grad2)" d="M185.432.063L96.44 17.501a3.268 3.268 0 0 0-2.634 3.014l-5.474 92.456a3.268 3.268 0 0 0 3.997 3.378l24.777-5.718c2.318-.535 4.413 1.507 3.936 3.838l-7.361 36.047c-.495 2.426 1.782 4.5 4.151 3.78l15.304-4.649c2.372-.72 4.652 1.36 4.15 3.788l-11.698 56.621c-.732 3.542 3.979 5.473 5.943 2.437l1.313-2.028l72.516-144.72c1.215-2.423-.88-5.186-3.54-4.672l-25.505 4.922c-2.396.462-4.435-1.77-3.759-4.114l16.646-57.705c.677-2.35-1.37-4.583-3.769-4.113Z"></path></svg>`,
  });

  // ── Config-driven files ──

  // CSS with theme colors and typography from config
  files.push({
    path: "src/index.css",
    content: generateIndexCSS(config.theme, config.typography),
  });

  // GitHub data JSON
  files.push({
    path: "src/data/github-data.json",
    content: JSON.stringify(githubData, null, 2),
  });

  // Utility functions
  files.push({
    path: "src/utils.ts",
    content: `import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`,
  });

  // Card UI component
  files.push({
    path: "src/components/ui/card.tsx",
    content: `import * as React from "react"
import { cn } from "../../utils"

const Card = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      "rounded-lg border bg-card text-card-foreground shadow-sm",
      className
    )}
    {...props}
  />
))
Card.displayName = "Card"

const CardHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("flex flex-col space-y-1.5 p-6", className)}
    {...props}
  />
))
CardHeader.displayName = "CardHeader"

const CardTitle = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      "text-2xl font-semibold leading-none tracking-tight",
      className
    )}
    {...props}
  />
))
CardTitle.displayName = "CardTitle"

const CardDescription = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("text-sm text-muted-foreground", className)}
    {...props}
  />
))
CardDescription.displayName = "CardDescription"

const CardContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
))
CardContent.displayName = "CardContent"

export { Card, CardHeader, CardTitle, CardDescription, CardContent }
`,
  });

  // Types for the generated portfolio
  files.push({
    path: "src/types.ts",
    content: `export interface SanitizedRepo {
  author: string;
  name: string;
  description: string;
  language: string | null | "";
  languageColor: string;
  stars: number;
  forks: number;
  isPinned: boolean;
  createdAt: string;
  updatedAt: string;
  pushedAt: string;
  activityDuration: string;
}

export interface PeriodMetrics {
  recentContributions: number;
  averageDailyCommits: number;
  weekendPercentage: number;
  mostActiveDay: string | null;
  weekdayWeekendBreakdown: { weekday: number; weekend: number };
  bestCommit: { date: string; count: number } | null;
}

export interface ContributionDetails {
  total: number;
  currentYear: number;
  currentStreak: number;
  longestStreak: number;
  activeYears: string[];
  yearOverYearChangePercentage: number | null;
  quarterOverQuarterChangePercentage: number | null;
  halfOverHalfChangePercentage: number | null;
  firstCommitDate: string | null;
  codingYears: string | null;
  pullRequests: { total: number; closed: number };
  issues: { total: number; closed: number };
  last6Months: PeriodMetrics;
  last1Year: PeriodMetrics;
  overall: PeriodMetrics;
}

export interface GitHubProfile {
  username: string;
  name: string;
  bio: string;
  avatar: string;
  profileUrl: string;
  location: string;
  company: string;
  blog: string;
  twitter: string;
  followers: number;
  following: number;
  publicRepos: number;
  publicGists: number;
  createdAt: string;
}

export interface LanguageDistribution {
  language: string;
  percentage: number;
  color: string;
}

export interface GitHubData {
  profile: GitHubProfile;
  profileUrl: string;
  contributions: ContributionDetails;
  sanitizedReposData: SanitizedRepo[];
  languageDistribution: LanguageDistribution[];
  totalStars: number;
  bestRepo: SanitizedRepo | null;
  mostActiveRepoThisMonth: SanitizedRepo | null;
  activelyMaintainedRepos: SanitizedRepo[];
  topActivelyUsedRepos: SanitizedRepo[];
}
`,
  });

  // ── Dynamic components driven by config ──

  files.push({
    path: "src/components/About.tsx",
    content: generateAboutComponent(config.componentStyles.about),
  });

  files.push({
    path: "src/components/GitHubStats.tsx",
    content: generateGitHubStatsComponent(
      config.componentStyles.githubStats,
      config.spacing
    ),
  });

  // ── App.tsx with CSS Grid layout from config ──

  files.push({
    path: "src/App.tsx",
    content: generateAppComponent(config),
  });

  return files;
}

/**
 * Generate App.tsx with CSS Grid layout driven by TemplateConfig.
 * Components are rendered as grid cells based on config.layout.components.
 */
function generateAppComponent(config: TemplateConfig): string {
  const { layout, spacing } = config;

  // Build component imports and JSX based on visible components
  const visibleComponents = layout.components.filter((c) => c.visible);

  const hasAbout = visibleComponents.some((c) => c.componentType === "About");
  const hasGitHubStats = visibleComponents.some(
    (c) => c.componentType === "GitHubStats"
  );

  // Build imports
  const imports: string[] = [];
  if (hasAbout) imports.push(`import About from "./components/About"`);
  if (hasGitHubStats)
    imports.push(`import { GitHubStats } from "./components/GitHubStats"`);

  // Build grid cells JSX
  const gridCells = visibleComponents
    .map((c) => {
      const styleProps: string[] = [];
      if (c.gridColumn) styleProps.push(`gridColumn: '${c.gridColumn}'`);
      if (c.gridRow) styleProps.push(`gridRow: '${c.gridRow}'`);
      const styleAttr =
        styleProps.length > 0 ? ` style={{ ${styleProps.join(", ")} }}` : "";

      if (c.componentType === "About") {
        return `        <div${styleAttr}>
          <About githubData={data} />
        </div>`;
      }
      if (c.componentType === "GitHubStats") {
        return `        <div${styleAttr}>
          <GitHubStats data={data} />
        </div>`;
      }
      return "";
    })
    .filter(Boolean)
    .join("\n\n");

  return `import { useState, useEffect } from "react"
import { Loader2 } from "lucide-react"
${imports.join("\n")}
import githubData from "./data/github-data.json"
import type { GitHubData } from "./types"

function App() {
  const [data, setData] = useState<GitHubData | null>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    setTimeout(() => {
      setData(githubData as GitHubData)
      setIsLoading(false)
    }, 100)
  }, [])

  if (isLoading || !data) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="w-6 h-6 animate-spin text-slate-400" />
          <p className="text-xs text-slate-500 font-medium">Loading...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-white">
      <style>{\`
        .portfolio-grid {
          display: grid;
          grid-template-columns: ${layout.gridColumnsMobile};
          gap: ${layout.gridGap};
          max-width: ${spacing.containerMaxWidth};
          margin: 0 auto;
          padding: ${spacing.containerPadding};
        }
        @media (min-width: ${layout.breakpoint}) {
          .portfolio-grid {
            grid-template-columns: ${layout.gridColumns};
          }
        }
      \`}</style>
      <div className="portfolio-grid">
${gridCells}
      </div>
    </div>
  )
}

export default App
`;
}
